dbdata:
  image: mysql:latest
  volumes:
    - /var/lib/mysql

dbserver:
  image: mysql:latest
  volumes_from:
    - dbdata
  environment:
    - MYSQL_ROOT_PASSWORD=Memzoh78
    - MYSQL_DATABASE=wp
    - MYSQL_USER=wp_demo
    - MYSQL_PASSWORD=Xumkos26

wpdata:
  image: wordpress:latest
  volumes:
    - /var/www/html

wpdemo:
  image: wordpress:latest
  links:
    - dbserver:mysql
  volumes_from:
    - wpdata
  ports:
    - "8080:80"
  environment:
    - WORDPRESS_DB_NAME=wp
    - WORDPRESS_DB_USER=wp_demo
    - WORDPRESS_DB_PASSWORD=Xumkos26